#!/usr/bin/env cwl-runner

cwlVersion: v1.0

class: CommandLineTool

requirements:
  - class: InlineJavascriptRequirement

hints:
  - class: DockerRequirement
    dockerPull: ACCOUNT/rnaseqc:VERSION

baseCommand: [run.sh]

inputs:
  - id: input_tar_gz
    type: File
    inputBinding:
      position: 1
    doc: Input file as a compressed archive. |
         This is the ouput generated by RNA-SeQC

  - id: sample_name
    type: string
    inputBinding:
      position: 2
    doc: Name of the sample

outputs:
  - id: output_file_json
    type: File
    outputBinding:
      glob: metrics.json

doc: |
  Run collect_rnaseqc_metrics.py to parse the ouput generated by RNA-SeQC
